<a href="https://colab.research.google.com/github/sujitx-vs/Deep-Neural-Networks---PGCP_AI/blob/main/DNN_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Day 1 - Deep Neural Network.

- Basics of Tensor Flow

In [ ]:
#Imports
import tensorflow as tf

## TensorFlow Variables & Tensors

In [ ]:
# Single number

scalar=tf.Variable(10)
print(scalar)
scalar.assign(20)
print(scalar)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>


In [ ]:
# Vector - 1D Array
vector = tf.constant([1,5,7])
print(vector)

tf.Tensor([1 5 7], shape=(3,), dtype=int32)


In [ ]:
# Matrix - 2D Array.
matrix = tf.constant([[1,2,3],[4,5,6]])
print(matrix)
print()

print(tf.reshape(matrix,(3,2)))
print()

print(tf.reshape(matrix,(-1)))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


##GradientTape (Automatic Differentiation)

In [ ]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
  y=x**2

grad = tape.gradient(y,x)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


## Three Types of Summation in constant

In [ ]:
a=tf.constant([
    [1,2],
    [3,4],
    [5,6]
])
# sum everything
print(tf.reduce_sum(a))
#sum along columns
print(tf.reduce_sum(a,axis=1))
#sum along rows
print(tf.reduce_sum(a,axis=0))

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor([ 3  7 11], shape=(3,), dtype=int32)
tf.Tensor([ 9 12], shape=(2,), dtype=int32)


## Activation Functions

In [ ]:
#relu
tf.keras.layers.Dense(64,activation='relu')
x=tf.constant([-2,0.0,3.0])
print(tf.nn.relu(x))

#sigmoid
tf.keras.layers.Dense(64,activation='sigmoid')
x=tf.constant([-2,0.0,3.0])
print(tf.nn.sigmoid(x))

tf.Tensor([0. 0. 3.], shape=(3,), dtype=float32)
tf.Tensor([0.11920292 0.5        0.95257413], shape=(3,), dtype=float32)


In [ ]:
x = tf.constant([1,2,3])
print(tf.cast(x, tf.float32))
print(tf.cast(x,tf.bool))

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


#Adam Optimizer

In [ ]:
w = tf.Variable(0.0)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)


In [ ]:
for i in range(10):
  with tf.GradientTape() as tape:
    loss=(w-4)**2
  grad = tape.gradient(loss,w)
  optimizer.apply_gradients([(grad,w)])
  print("step:",i,
        "weight:",round(w.numpy(),2),
        "loss:",round(loss.numpy(),4)
  )

step: 0 weight: 0.8 loss: 16.0
step: 1 weight: 2.16 loss: 10.24
step: 2 weight: 3.75 loss: 3.3856
step: 3 weight: 5.23 loss: 0.0615
step: 4 weight: 6.32 loss: 1.5237
step: 5 weight: 6.84 loss: 5.3902
step: 6 weight: 6.73 loss: 8.0423
step: 7 weight: 6.09 loss: 7.4612
step: 8 weight: 5.1 loss: 4.3734
step: 9 weight: 3.98 loss: 1.2029


#SGD+Momentum Optimizer

In [ ]:
w = tf.Variable(0.0)

optimizer = tf.keras.optimizers.SGD(learning_rate=0.1,momentum=0.9)


In [ ]:
for i in range(10):
  with tf.GradientTape() as tape:
    loss=(w-4)**2
  grad = tape.gradient(loss,w)
  optimizer.apply_gradients([(grad,w)])
  print("step:",i,
        "weight:",round(w.numpy(),2),
        "loss:",round(loss.numpy(),4)
  )

step: 0 weight: 2.98 loss: 0.0003
step: 1 weight: 2.29 loss: 1.0343
step: 2 weight: 2.0 loss: 2.9347
step: 3 weight: 2.15 loss: 3.9878
step: 4 weight: 2.65 loss: 3.4337
step: 5 weight: 3.37 loss: 1.8303
step: 6 weight: 4.14 loss: 0.3997
step: 7 weight: 4.81 loss: 0.0204
step: 8 weight: 5.25 loss: 0.6591
step: 9 weight: 5.4 loss: 1.5665


#RMSProp Optimizer

In [ ]:
w = tf.Variable(0.0)

optimizer = tf.keras.optimizers.RMSprop(learning_rate=0.1,rho=0.9)

In [ ]:
for i in range(10):
  with tf.GradientTape() as tape:
    loss=(w-4)**2
  grad = tape.gradient(loss,w)
  optimizer.apply_gradients([(grad,w)])
  print("step:",i,
        "weight:",round(w.numpy(),2),
        "loss:",round(loss.numpy(),4)
  )

step: 0 weight: 0.32 loss: 16.0
step: 1 weight: 0.54 loss: 13.5702
step: 2 weight: 0.72 loss: 11.9959
step: 3 weight: 0.87 loss: 10.7837
step: 4 weight: 1.01 loss: 9.7827
step: 5 weight: 1.14 loss: 8.9238
step: 6 weight: 1.26 loss: 8.1693
step: 7 weight: 1.38 loss: 7.4956
step: 8 weight: 1.48 loss: 6.8873
step: 9 weight: 1.59 loss: 6.3332
