<a href="https://colab.research.google.com/github/sujitx-vs/Deep-Neural-Networks---PGCP_AI/blob/main/DNN_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 2 - Deep Neural Network.
- Basics of Pytorch

In [ ]:
#imports
import pandas as pd
import numpy as np
import torch

## Tensors

In [ ]:
# Single Number -scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [ ]:
# Vector - 1D Array
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
# Matrix - 3D Array
matrix = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(matrix)
print(matrix.shape)
print("dimension:",matrix.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
dimension: 3


##Autograd (Automatic Gradients)

In [ ]:
x = torch.tensor(3.0,requires_grad=True)
y = x**2
y.backward()
x.grad

tensor(6.)

##Multiple Variable Gradients

In [ ]:
w = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(1.0,requires_grad=True)
y = 3*w**2+2*b**4
y.backward()
print(w.grad)
print(b.grad)

tensor(12.)
tensor(8.)


##Tensor Operations

In [ ]:
a = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

# column wise sum
print(sum(a))

# overall mean
print(torch.mean(a.float()))

tensor([ 9, 12])
tensor(3.5000)


##SGD+Momentum Optimizer

In [ ]:
w = torch.tensor(
    0.0,
    requires_grad=True
  )

optimizer = torch.optim.SGD([w],lr=0.1,momentum=0.9)

for i in range(15):
  loss = (w-5)**2
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  print("weight:",round(w.item(),2),end=" ")
  print("loss:",round(loss.item(),2))


weight: 1.0 loss: 25.0
weight: 2.7 loss: 16.0
weight: 4.69 loss: 5.29
weight: 6.54 loss: 0.1
weight: 7.9 loss: 2.38
weight: 8.54 loss: 8.42
weight: 8.41 loss: 12.57
weight: 7.61 loss: 11.66
weight: 6.37 loss: 6.83
weight: 4.98 loss: 1.88
weight: 3.73 loss: 0.0
weight: 2.86 loss: 1.62
weight: 2.5 loss: 4.59
weight: 2.68 loss: 6.23
weight: 3.31 loss: 5.37


## RMSProp Optimizer

In [ ]:
w = torch.tensor(
    0.0,
    requires_grad=True
  )

optimizer = torch.optim.RMSprop([w],lr=0.1,alpha=0.9)

for i in range(15):
  loss = (w-5)**2
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  print("weight:",round(w.item(),2),end=" ")
  print("loss:",round(loss.item(),2))

# model = nn.Sequential(
#     nn.Linear(8,4),
#     nn.ReLU(),
#     nn.Linear(4,1),
#     nn.LogSoftmax(dim=1)
# )

weight: 0.32 loss: 25.0
weight: 0.54 loss: 21.94
weight: 0.72 loss: 19.91
weight: 0.88 loss: 18.31
weight: 1.02 loss: 16.97
weight: 1.16 loss: 15.81
weight: 1.28 loss: 14.77
weight: 1.4 loss: 13.83
weight: 1.51 loss: 12.97
weight: 1.62 loss: 12.17
weight: 1.72 loss: 11.43
weight: 1.82 loss: 10.74
weight: 1.92 loss: 10.09
weight: 2.02 loss: 9.47
weight: 2.11 loss: 8.9
